spring.application.name=underprint
spring.datasource.url=jdbc:postgresql://localhost:5433/underprint
spring.datasource.username=underprint
spring.datasource.password=underprint123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true